### ISSUE TITLE
open dialog in parent window

### ISSUE THREAD

**Issue by gkreddy** [nzbin/magnify#4]
Thank you for the plugin. It works awesome. i've one issue, my pictures are present inside the iframe when i click on picture it opens a dialog/modal inside the iframe. how can i get this modal displayed out of iframe(or in the parent window)

Thanks in advance

**Comment by nzbin** [comment]
@gkreddy  Glad I should help. In general, it could't open the modal out of iframe if you set plugin in iframe. But I think you can reference plugin file out of iframe and make some hidden elements which can get events of images in iframe. You can try!

**Comment by gkreddy** [comment]
Thank you for your reply. I'm new to this, do you have any working example codepen/jsfiddle? thank you in advance

**Comment by Lupeipei** [comment]
Actually, I just have an opposite issue. Here is the scenario:
There are two layers on my pages. When I click the image, the first layer comes out with some buttons in it. then I click one of the buttons, the second layer(magnify used on the layer) comes out with some images in it, then I click one of the images, nothing happens. what I expect is when I click a image, I can view them just like in windows. the problem is when I close all layers, the modal come out. I wonder if this plugin can't play well  with multiple layers? Any suggestions to  tackle the problem is welcome.
Thank you in advance.
PS. Have I made myself clear? hope my explanation in Chinese can make a better understanding. 
页面总共有2个弹层，我点击页面的某张图片，会弹出第一个弹层，这个弹层上有一些按钮，点击其中的一个按钮，会弹出第二个弹层，第二个弹层里面是三张图片，我点击任意一张图片，希望可以得到类似window下的图片预览结果，在第二个弹层里面我使用了您的magnify，但是点击图片时无效，等到我关闭了所有弹层时，却弹出了这个plugin的modal 。请问多弹层的情况下，如何正确使用这个plugin？

**Comment by nzbin** [comment]
@Lupeipei 请检查是否是打开的弹层遮住了 magnify 的 modal，如果是的话，可以手动调整 modal 的 z-index

**Comment by Lupeipei** [comment]
@nzbin 好，我试试，谢谢！

**Comment by Lupeipei** [comment]
@nzbin 调整了z-index ，完美解决，太赞了！谢谢！
